name: Tailscale + Waydroid

on:
  workflow_dispatch:

jobs:
  test-tailscale:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Tailscale (correct way)
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start tailscaled in userspace mode
        run: |
          nohup sudo tailscaled --tun=userspace-networking \
            --socks5-server=localhost:1055 \
            --outbound-http-proxy-listen=localhost:1056 > tailscaled.log 2>&1 &

      - name: Connect to Tailscale
        run: |
          sleep 5
          sudo tailscale up --authkey ${{ secrets.TS_AUTHKEY }} --ssh --reset

      - name: Get Tailscale IP
        run: tailscale ip -4

      - name: Keep alive
        run: sleep 7200
