name: Tailscale + Waydroid

on:
  workflow_dispatch:

jobs:
  test-tailscale:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Tailscale (correct way)
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start tailscaled in userspace mode
        run: |
          nohup sudo tailscaled --tun=userspace-networking \
            --socks5-server=localhost:1055 \
            --outbound-http-proxy-listen=localhost:1056 > tailscaled.log 2>&1 &

      - name: Connect to Tailscale
        run: |
          sleep 5
          sudo tailscale up --authkey ${{ secrets.TS_AUTHKEY }} --ssh --reset

      - name: Get Tailscale IP
        run: tailscale ip -4

      - name: Install Waydroid
        run: |
          sudo apt update
          sudo apt install -y curl ca-certificates gnupg \
            lxc lxd python3-pip android-tools-adb \
            x11-utils weston xwayland dbus-x11

          curl https://repo.waydro.id | sudo bash
          sudo apt install -y waydroid
          sudo waydroid init -s GAPPS

      - name: Start Waydroid container
        run: |
          sudo systemctl start waydroid-container
          sleep 10
          sudo waydroid container start
          sleep 5
          sudo waydroid session start &
          sleep 15

      - name: Enable ADB in Waydroid
        run: |
          sudo waydroid prop set persist.adb.tcp.port 5555
          sleep 5
          sudo waydroid session start &
          sleep 10
          adb connect 127.0.0.1:5555 || true
          adb devices || true

      - name: Keep alive
        run: sleep 7200
